name: cerdo.vinarium
favicon: null
layout_spectrum: 0.48773
typography_spectrum: 0.14809475652873516
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0
  lightness: 0.36574977822601795
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
