typography_spectrum: 0.844595
color:
  brandColors:
    - '#fccda4'
    - '#3b3422'
    - '#7e6761'
    - '#100703'
    - '#f6f6f6'
  brandStrength: 0.4375
  lightness: 0.375
  saturation: 0.625
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.44848
analytics:
  google: null
  facebook: null
  twitter: null
name: cerdo.vinarium
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: O Vinarium Lendava
    id: 1cd16803-df7e-4968-8ab5-99113e45cb1c
    type: content
favicon: null
purpose: []
