name: cerdo.vinarium
favicon: null
layout_spectrum: 0.48773
typography_spectrum: 0.25164
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4d4640'
    - '#ebd7f0'
    - '#887240'
    - '#b19ba8'
    - '#120604'
  brandStrength: 0
  lightness: 0.36574977822601795
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
