name: cerdo.vinarium
favicon: null
layout_spectrum: 0.49759
typography_spectrum: 0.2509
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fccda4'
    - '#3b3422'
    - '#7e6761'
    - '#100703'
    - '#f6f6f6'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
