name: cerdo.vinarium
favicon: null
layout_spectrum: 0.25211
typography_spectrum: 0.25164
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b2bece'
    - '#6d5e25'
    - '#2a2917'
    - '#9c8b3f'
    - '#fae3bb'
  brandStrength: 0
  lightness: 0.25
  saturation: 0
  rhythmicContrast: 1
purpose: []
