analytics: {}
color:
  brandColors:
    - '#fccda4'
    - '#3b3422'
    - '#7e6761'
    - '#100703'
    - '#f6f6f6'
  brandStrength: 0
  lightness: 0.5
  rhythmicContrast: 0.5
  saturation: 0.5
cta: {}
layout_spectrum: 0.570946
name: cerdo.vinarium
opengraph: {}
purpose: []
typography_spectrum: 0.844595
